### ISSUE TITLE
Gust Data not Available if Not Sent by Hardware

### ISSUE THREAD

**Issue by techfixpros** [matthewwall/weewx-meteotemplate#3]
Gust data is not sending via API using this method. It is still being stored in both WeeWx, WeeWxWD, and MeteoTemplate DB's. Jachym @ Meteotemplate requested the meteotemplateLive.txt which shows:
`{"TBAT":0,"B":202,"RR":0,"SW":"weewx-3.7.1","R":0,"U":1500836151,"W":8.45,"TBATTime":1500836152,"BTime":1500836152,"RRTime":1500836152,"SWTime":1500836152,"RTime":1500836152,"UTime":1500836152,"WTime":1500836152,"H":38,"HTime":1500836152,"T":33.39,"TTime":1500836152,"TIN":34.95,"TINTime":1500836152,"UGP":912.375,"UGPTime":1500836152,"P":1010.354,"PTime":1500836152,"D":17.2,"DTime":1500836152,"A":34.2,"ATime":1500836152}`

No gust data is present. The following also show that gust is not available in the API file.
![gust1](https://user-images.githubusercontent.com/7028086/28502021-e4ca3f28-6fae-11e7-996d-4c50a453dec2.jpg)
![gust2](https://user-images.githubusercontent.com/7028086/28502026-edf731be-6fae-11e7-9d3f-31a6d80cde2e.jpg)

Meteotemplate's DB is populating Gust and it is available in the template everywhere the data is pulled from the DB, but not in the gauges. Per Jachym, "...that is because if it has no G, it just uses max W, but in the api gust is not present."

I am using an Acurite VI, and am aware that it does not send gust, but the WeeWxWD extension does calculate it and sent it so that it shows in the gauge.

**Comment by matthewwall** [comment]
what hardware are you using?  does the hardware emit a value for wind gust?

**Comment by techfixpros** [comment]
Sorry, I just updated the issue. I am using an Acurite VI, and am aware that it does not send gust, but the WeeWxWD extension does calculate it and sent it so that it shows in the gauge.

**Comment by matthewwall** [comment]
if the hardware does not emit a value for guest in loop packets, then there is nothing to send.  software can calculate a max value for archive records, but not for loop packets.
