### ISSUE TITLE
Weewx-meteotemplate data loss when computer turned off

### ISSUE THREAD

**Issue by flopezlosada** [matthewwall/weewx-meteotemplate#5]
Hi. I'm starting to use weewx with my new station. I have the station connected to a computer that I do not always have on. In the configuration of weewx I have set "record_generation = archive" so that each time I turn it on I will load the data saved in the station (FineOffset WH1080) and not lose data when the computer is turned off. And it works correctly.
The fact is that I'm using weewx-meteotemplate to load the data in a meteotemplate template and only load the data when the computer is on, not as weewx that also loads the data that is missing from when the computer is turned off. That is, I lose data in meteotemplate.
Is there any way to load the missing data? or some way that works the same as weewx?
I put in the configuration of weewx-meteotemplate "binding = archive" and "binding = loop" and neither works.
Thank you

**Comment by matthewwall** [comment]
unfortunately, weewx does not *yet* do what you ask for.

the wunderfixer utility is basically what you need, but it only works with weather underground.

imagine a generic version of wunderfixer called `wee_upload`.  it would synchronize data from your weewx database to any server-based database, such as wu or meteotemplate or influx or emoncms.

in fact, i am working on this utility now for influx and emoncms.  it should not be too difficult to make it work with meteotemplate as well.

meanwhile, you should contact luc.  he has written a python program that does this, but only for meteotemplate.

http://www.meteotemplate.com/forum/viewtopic.php?f=43&t=385
