### ISSUE TITLE
Not working with weewx multi?

### ISSUE THREAD

**Issue by SylvainMartel** [matthewwall/weewx-meteotemplate#7]
The installation of weewx-meteotemplate seems to have worked, and I modified the conf file(StdRestful section) of one of the station, but I see no message that weewx is trying to upload message to the template.  
[[Meteotemplate]]
        server_url = edited
        password = edited

Since I am using weewx-multi, is there something else to modify?

Here is the syslog
    Aug  8 17:28:00 Pi2 weewx-sto2[18375]: engine: Using binding 'wx_binding' to database 'sto2'
    Aug  8 17:28:00 Pi2 weewx-sto2[18375]: manager: Starting backfill of daily summaries
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: restx: StationRegistry: Registration not requested.
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: restx: Wunderground: Posting not enabled.
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: restx: PWSweather: Posting not enabled.
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: restx: CWOP: Posting not enabled.
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: restx: WOW: Posting not enabled.
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: restx: AWEKAS: Posting not enabled.
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: engine: Starting up weewx version 3.8.0
Aug  8 17:28:00 Pi2 weewx-sto2[18375]: engine: Starting main packet loop.

**Comment by matthewwall** [comment]
be sure that weewx-meteotemplate is in the list of services:

```
[Engine]
    [[Services]]
        ...
        restful_services = ..., user.meteotemplate.Meteotemplate
```

**Comment by SylvainMartel** [comment]
That was it, thanks!  I had browsed through the modified weewx.conf but had missed that one.

Thanks again

Aug  8 17:47:00 Pi2 weewx-sto2[18851]: restx: Meteotemplate: service version is 0.9
Aug  8 17:47:00 Pi2 weewx-sto2[18851]: restx: Meteotemplate: Data will be uploaded to
